class FallbackData {
  static const Map<String, List<Map<String, String>>> lists = {
    'Starter': [
      {'english': 'apple', 'hebrew': 'תפוח', 'syllables': 'ap.ple'}, 
      {'english': 'ball', 'hebrew': 'כדור', 'syllables': 'ball'}, 
      {'english': 'cat', 'hebrew': 'חתול', 'syllables': 'cat'}, 
      {'english': 'dog', 'hebrew': ' כלב', 'syllables': 'dog'}, 
      {'english': 'egg', 'hebrew': '🥚', 'syllables': 'egg'}, 
      {'english': 'fish', 'hebrew': 'דג', 'syllables': 'fish'}, 
      {'english': 'green', 'hebrew': 'ירוק', 'syllables': 'green'}, 
      {'english': 'hat', 'hebrew': 'כובע', 'syllables': 'hat'}, 
      {'english': 'ice', 'hebrew': ' קרח', 'syllables': 'ice'}, 
      {'english': 'jump', 'hebrew': 'קפיצה', 'syllables': 'jump'},
      {'english': 'kite', 'hebrew': 'עפיפון', 'syllables': 'kite'}, 
      {'english': 'lemon', 'hebrew': '🍋', 'syllables': 'lem.on'}, 
      {'english': 'moon', 'hebrew': 'ירח', 'syllables': 'moon'}, 
      {'english': 'nest', 'hebrew': 'קן', 'syllables': 'nest'}, 
      {'english': 'orange', 'hebrew': ' כתום', 'syllables': 'or.ange'},
      {'english': 'pig', 'hebrew': '豚', 'syllables': 'pig'}, 
      {'english': 'queen', 'hebrew': 'מלכה', 'syllables': 'queen'}, 
      {'english': 'red', 'hebrew': 'אדום', 'syllables': 'red'}, 
      {'english': 'sun', 'hebrew': 'שמש', 'syllables': 'sun'}, 
      {'english': 'tree', 'hebrew': 'עץ', 'syllables': 'tree'}
    ],
    'Explorer': [
      {'english': 'airport', 'hebrew': 'נמל תעופה', 'syllables': 'air.port'}, 
      {'english': 'bridge', 'hebrew': 'גשר', 'syllables': 'bridge'}, 
      {'english': 'camera', 'hebrew': 'מצלמה', 'syllables': 'cam.er.a'}, 
      {'english': 'doctor', 'hebrew': 'רופא', 'syllables': 'doc.tor'}, 
      {'english': 'engine', 'hebrew': 'מנוע', 'syllables': 'en.gine'},
      {'english': 'forest', 'hebrew': 'יער', 'syllables': 'for.est'}, 
      {'english': 'garden', 'hebrew': ' גן', 'syllables': 'gar.den'}, 
      {'english': 'honey', 'hebrew': 'דבש', 'syllables': 'hon.ey'}, 
      {'english': 'island', 'hebrew': 'אי', 'syllables': 'is.land'}, 
      {'english': 'jungle', 'hebrew': 'ג׳ונגל', 'syllables': 'jun.gle'},
      {'english': 'kitchen', 'hebrew': 'מטבח', 'syllables': 'kitch.en'}, 
      {'english': 'library', 'hebrew': 'ספריה', 'syllables': 'li.brary'}, 
      {'english': 'market', 'hebrew': 'שוק', 'syllables': 'mar.ket'}, 
      {'english': 'night', 'hebrew': 'לילה', 'syllables': 'night'}, 
      {'english': 'ocean', 'hebrew': 'ים', 'syllables': 'o.cean'},
      {'english': 'pencil', 'hebrew': 'עפרון', 'syllables': 'pen.cil'}, 
      {'english': 'robot', 'hebrew': 'רובוט', 'syllables': 'ro.bot'}, 
      {'english': 'school', 'hebrew': 'בית ספר', 'syllables': 'school'}, 
      {'english': 'ticket', 'hebrew': 'כרטיס', 'syllables': 'tick.et'}, 
      {'english': 'umbrella', 'hebrew': '☂️', 'syllables': 'um.brel.la'}
    ],
    'Challenger': [
      {'english': 'adventure', 'hebrew': 'הרפתקה', 'syllables': 'ad.ven.ture'}, 
      {'english': 'beautiful', 'hebrew': 'יפה', 'syllables': 'beau.ti.ful'}, 
      {'english': 'celebrate', 'hebrew': 'לחגוג', 'syllables': 'cel.e.brate'}, 
      {'english': 'dangerous', 'hebrew': 'מסוכן', 'syllables': 'dan.ger.ous'}, 
      {'english': 'elephant', 'hebrew': 'פיל', 'syllables': 'el.e.phant'},
      {'english': 'festival', 'hebrew': 'פֶּסטִיָּל', 'syllables': 'fes.ti.val'}, 
      {'english': 'gratitude', 'hebrew': 'הכרת תודה', 'syllables': 'grat.i.tude'}, 
      {'english': 'happiness', 'hebrew': 'שמחה', 'syllables': 'hap.pi.ness'}, 
      {'english': 'important', 'hebrew': 'חשוב', 'syllables': 'im.por.tant'}, 
      {'english': 'journey', 'hebrew': 'מסע', 'syllables': 'jour.ney'},
      {'english': 'knowledge', 'hebrew': 'ידע', 'syllables': 'knowl.edge'}, 
      {'english': 'landscape', 'hebrew': 'נוף', 'syllables': 'land.scape'}, 
      {'english': 'mountain', 'hebrew': 'הר', 'syllables': 'moun.tain'}, 
      {'english': 'navigation', 'hebrew': 'ניווט', 'syllables': 'nav.i.ga.tion'}, 
      {'english': 'opposite', 'hebrew': 'מנוגד', 'syllables': 'op.po.site'},
      {'english': 'practice', 'hebrew': 'תרגיל', 'syllables': 'prac.tice'}, 
      {'english': 'question', 'hebrew': ' שאלה', 'syllables': 'ques.tion'}, 
      {'english': 'remember', 'hebrew': 'זכור', 'syllables': 're.mem.ber'}, 
      {'english': 'sandwich', 'hebrew': 'כריך', 'syllables': 'sand.wich'}, 
      {'english': 'telephone', 'hebrew': 'טלפון', 'syllables': 'tel.e.phone'}
    ],
  };
}
