class FallbackData {
  static const Map<String, List<Map<String, String>>> lists = {
    'Starter': [
      {'english': 'apple', 'hebrew': 'תפוח'}, 
      {'english': 'ball', 'hebrew': 'כדור'}, 
      {'english': 'cat', 'hebrew': 'חתול'}, 
      {'english': 'dog', 'hebrew': ' כלב'}, 
      {'english': 'egg', 'hebrew': '🥚'}, 
      {'english': 'fish', 'hebrew': 'ปลา'}, 
      {'english': 'green', 'hebrew': 'ירוק'}, 
      {'english': 'hat', 'hebrew': 'כובע'}, 
      {'english': 'ice', 'hebrew': ' קרח'}, 
      {'english': 'jump', 'hebrew': 'קפיצה'},
      {'english': 'kite', 'hebrew': 'עפיפון'}, 
      {'english': 'lemon', 'hebrew': '🍋'}, 
      {'english': 'moon', 'hebrew': 'ירח'}, 
      {'english': 'nest', 'hebrew': 'קן'}, 
      {'english': 'orange', 'hebrew': ' כתום'},
      {'english': 'pig', 'hebrew': '豚'}, 
      {'english': 'queen', 'hebrew': 'מלכה'}, 
      {'english': 'red', 'hebrew': 'אדום'}, 
      {'english': 'sun', 'hebrew': 'שמש'}, 
      {'english': 'tree', 'hebrew': 'עץ'}
    ],
    'Explorer': [
      {'english': 'airport', 'hebrew': 'נמל תעופה'}, 
      {'english': 'bridge', 'hebrew': 'גשר'}, 
      {'english': 'camera', 'hebrew': 'מצלמה'}, 
      {'english': 'doctor', 'hebrew': 'רופא'}, 
      {'english': 'engine', 'hebrew': 'מנוע'},
      {'english': 'forest', 'hebrew': 'יער'}, 
      {'english': 'garden', 'hebrew': ' גן'}, 
      {'english': 'honey', 'hebrew': 'דבש'}, 
      {'english': 'island', 'hebrew': 'אי'}, 
      {'english': 'jungle', 'hebrew': 'ג׳ונגל'},
      {'english': 'kitchen', 'hebrew': 'מטבח'}, 
      {'english': 'library', 'hebrew': 'ספריה'}, 
      {'english': 'market', 'hebrew': 'שוק'}, 
      {'english': 'night', 'hebrew': 'לילה'}, 
      {'english': 'ocean', 'hebrew': 'ים'},
      {'english': 'pencil', 'hebrew': 'עפרון'}, 
      {'english': 'robot', 'hebrew': 'רובוט'}, 
      {'english': 'school', 'hebrew': 'בית ספר'}, 
      {'english': 'ticket', 'hebrew': 'כרטיס'}, 
      {'english': 'umbrella', 'hebrew': '☂️'}
    ],
    'Challenger': [
      {'english': 'adventure', 'hebrew': 'הרפתקה'}, 
      {'english': 'beautiful', 'hebrew': 'יפה'}, 
      {'english': 'celebrate', 'hebrew': 'לחגוג'}, 
      {'english': 'dangerous', 'hebrew': 'מסוכן'}, 
      {'english': 'elephant', 'hebrew': 'פיל'},
      {'english': 'festival', 'hebrew': 'פֶּסטִיָּל'}, 
      {'english': 'gratitude', 'hebrew': 'הכרת תודה'}, 
      {'english': 'happiness', 'hebrew': 'שמחה'}, 
      {'english': 'important', 'hebrew': 'חשוב'}, 
      {'english': 'journey', 'hebrew': 'מסע'},
      {'english': 'knowledge', 'hebrew': 'ידע'}, 
      {'english': 'landscape', 'hebrew': 'נוף'}, 
      {'english': 'mountain', 'hebrew': 'הר'}, 
      {'english': 'navigation', 'hebrew': 'ניווט'}, 
      {'english': 'opposite', 'hebrew': 'מנוגד'},
      {'english': 'practice', 'hebrew': 'תרגיל'}, 
      {'english': 'question', 'hebrew': ' שאלה'}, 
      {'english': 'remember', 'hebrew': 'זכור'}, 
      {'english': 'sandwich', 'hebrew': 'כריך'}, 
      {'english': 'telephone', 'hebrew': 'טלפון'}
    ],
  };
}
